apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: website
  template:
    metadata:
      labels:
        instance: website
    spec:
      containers:
      - name: website
        image: gcr.io/devops-interview-242708/nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 4Gi
            cpu: 500m
          limits:
            memory: 5Gi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  ports:
  - port: 80
  selector:
    instance: website
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: loadbalancer
spec:
  backend:
    serviceName: website
    servicePort: 80
